"""fixed table users

Revision ID: c01098e84c05
Revises: d7512f59dbd8
Create Date: 2023-10-15 14:50:20.381014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01098e84c05'
down_revision = 'd7512f59dbd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
