"""fixed

Revision ID: 59215b5578a9
Revises: be7d055c9593
Create Date: 2023-06-28 12:24:23.875819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59215b5578a9'
down_revision = 'be7d055c9593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
