"""fix

Revision ID: d7512f59dbd8
Revises: 0e008629e844
Create Date: 2023-06-29 10:13:20.712233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7512f59dbd8'
down_revision = '0e008629e844'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hardware_cpu_key', 'hardware', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hardware_cpu_key', 'hardware', ['cpu'])
    # ### end Alembic commands ###
